name: operator-auto-release
on:
  workflow_dispatch:
  push:




jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - run: docker --version


      - name: Install Operator-Sdk
        run: |
          set -x
          sudo curl -L -o /operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu"
          sudo chmod +x /operator-sdk
          sudo /operator-sdk version